version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - network.dockerclass

  sqlpad:
    image: sqlpad/sqlpad:latest
    container_name: dockertraining
    environment:
      SQLPAD_ADMIN: admin
      SQLPAD_ADMIN_PASSWORD: admin123
      SQLPAD_AUTH_DISABLED: "false"
      SQLPAD_APP_LOG_LEVEL: info
      SQLPAD_DB_PATH: /var/lib/sqlpad
    ports:h
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - network.dockerclass

volumes:
  postgres_data:

networks:
  network.dockerclass:
