apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-deployment
  labels:
    app: task
spec:
  replicas: 2  # Initial number of pods (can be adjusted by HPA)
  selector:
    matchLabels:
      app: task
  template:
    metadata:
      labels:
        app: task
    spec:
      containers:
      - name: task
        image: kenedymanga442/task:latest  # Docker Hub image
        ports:
        - containerPort: 3000              # App listens on port 3000

        # Vertical Scaling: defines min and max CPU/memory per pod
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: task-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: task-deployment
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60

---

apiVersion: v1
kind: Service
metadata:
  name: task-service
spec:
  selector:
    app: task
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30080  # 