# Create the namespace
apiVersion: v1
kind: Namespace
metadata:
  name: rbac-ns
 
---
 
# Create the ServiceAccount in rbac-ns
apiVersion: v1
kind: ServiceAccount
metadata:
  name: myapp-sa
  namespace: rbac-ns
 
---
 
# Create the Role that allows listing pods in rbac-ns
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: rbac-ns
  name: pod-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
 
---
 
# Bind the Role to the ServiceAccount
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods-binding
  namespace: rbac-ns
subjects:
- kind: ServiceAccount
  name: myapp-sa
  namespace: rbac-ns
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
 
---
 
# ClusterRole to read pods in all namespaces
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-pod-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
 
---
 
# Bind ClusterRole to user alice
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: alice-read-all-pods
subjects:
- kind: User
  name: alice
roleRef:
  kind: ClusterRole
  name: cluster-pod-reader
  apiGroup: rbac.authorization.k8s.io